### PR TITLE
learning how to commit

### PR DESCRIPTION
**Pull request by rikarumi**
1. Learning how to create a branch
2. Learning how to commit changes

### CODE REVIEW

**Comment by firewalker06** [comment]
Ah, this commit is still using my Git credential :laughing:

**Comment by firewalker06** [comment]
LGTM, please merge this :+1:

**Comment by rikarumi** [comment]
alright

**Comment by firewalker06** [comment]
Click "merge pull request" button in here

**Comment by rikarumi** [comment]
can't find the button. Is it because the access level? 
untitled

**Comment by firewalker06** [comment]
Congrats for first PR :tada:

**Pull request merged**
